version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - docker-hub-credencials

jobs:
  build:
    docker:
      - image: circleci/node:12.19.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
    - checkout
    - run:
        name: dependencies
        command: |
          npm i

    - run:
        name: lint
        command: |
          npm run test

    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules

    - deploy:
        command: |
          sudo apt-get -y -qq install awscli
          if [ "${CIRCLE_BRANCH}" != "master" ]; then
            cp -p robots.txt src
            npm run s3sync:develop
          else
            export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION_PRODUCTION}
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PRODUCTION}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PRODUCTION}
            npm run s3sync:production
          fi
